# .goreleaser.yaml
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - arm
      - amd64
    goarm:
      - 7

dockers:
- image_templates:
  - "ghcr.io/hoodlum/{{ .ProjectName }}:{{ .Version }}-amd64"
  use: buildx
  build_flag_templates:
  - --pull
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/hoodlum/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/hoodlum/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
#  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
#  - --label=org.opencontainers.image.licenses=MIT  
