# .goreleaser.yaml
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7

dockers:
- image_templates:
  - 'hoodlum/vz-mqtt-dbus-gateway:{{ .Tag }}-amd64'
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
