name: goreleaser

on:
  push:
    tags:
      - '*'

#permissions:
#  contents: write
#  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      -
        name: Test
        run: echo ${{secrets.GH_PAT}} | sed 's/./& /g'
      -
        name: Login to github package registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}        
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          #GOOS: linux
          #GOARCH: arm
          #GOARM: 7
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: vz-mqtt-dbus-gateway
          path: myfolder/dist/*
